package xyz.xenondevs.vetric

import xyz.xenondevs.bytebase.jvm.JavaArchive
import xyz.xenondevs.vetric.cli.command.CommandManager
import xyz.xenondevs.vetric.config.VetricConfig
import xyz.xenondevs.vetric.cli.terminal.info

object Vetric {
    
    const val VERSION = "0.0.1"
    
    var debug = false
    
    @Volatile
    var exit = false
    
    fun run(config: VetricConfig) {
        val jar = JavaArchive(config.input)
        applyTransformers(jar, config)
        saveOutput(jar, config)
    }
    
    private fun applyTransformers(jar: JavaArchive, config: VetricConfig) {
        config.transformers.forEach { transformer ->
            info("Loading transformer configs...")
            transformer.loadConfig(config[transformer])
            transformer.prepare(jar)
        }
        // Second loop to properly obfuscate any methods generated by Transformer#prepare
        config.transformers.forEach { transformer ->
            info("Applying " + transformer.name + "...")
            transformer.transform(jar)
        }
    }
    
    private fun saveOutput(jar: JavaArchive, config: VetricConfig) {
        info("Saving jar...")
        jar.writeFile(config.output)
    }
    
}